import mysql.connector as m
books = [
    ["To Kill a Mockingbird", "Harper Lee", 350, 15],
    ["1984", "George Orwell", 300, 10],
    ["Pride and Prejudice", "Jane Austen", 280, 20],
    ["The Great Gatsby", "F. Scott Fitzgerald", 250, 8],
    ["Moby-Dick", "Herman Melville", 400, 5],
    ["War and Peace", "Leo Tolstoy", 500, 7],
    ["The Catcher in the Rye", "J.D. Salinger", 270, 12],
    ["Crime and Punishment", "Fyodor Dostoevsky", 450, 6],
    ["The Odyssey", "Homer", 300, 14],
    ["Brave New World", "Aldous Huxley", 320, 11],
    ["Wuthering Heights", "Emily Brontë", 290, 9],
    ["Jane Eyre", "Charlotte Brontë", 310, 16],
    ["Anna Karenina", "Leo Tolstoy", 480, 4],
    ["The Brothers Karamazov", "Fyodor Dostoevsky", 470, 3],
    ["The Iliad", "Homer", 340, 13],
    ["Les Misérables", "Victor Hugo", 550, 2],
    ["The Hobbit", "J.R.R. Tolkien", 280, 20],
    ["The Lord of the Rings", "J.R.R. Tolkien", 600, 15],
    ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 400, 18],
    ["Harry Potter and the Chamber of Secrets", "J.K. Rowling", 420, 17],
    ["Harry Potter and the Prisoner of Azkaban", "J.K. Rowling", 430, 15],
    ["Harry Potter and the Goblet of Fire", "J.K. Rowling", 450, 14],
    ["Harry Potter and the Order of the Phoenix", "J.K. Rowling", 500, 10],
    ["Harry Potter and the Half-Blood Prince", "J.K. Rowling", 480, 12],
    ["Harry Potter and the Deathly Hallows", "J.K. Rowling", 520, 9],
    ["The Alchemist", "Paulo Coelho", 300, 25],
    ["The Kite Runner", "Khaled Hosseini", 320, 18],
    ["A Thousand Splendid Suns", "Khaled Hosseini", 350, 12],
    ["Life of Pi", "Yann Martel", 290, 20],
    ["The Road", "Cormac McCarthy", 310, 14],
    ["The Book Thief", "Markus Zusak", 380, 13],
    ["The Fault in Our Stars", "John Green", 270, 22],
    ["Looking for Alaska", "John Green", 250, 16],
    ["Paper Towns", "John Green", 260, 18],
    ["An Abundance of Katherines", "John Green", 240, 19],
    ["Turtles All the Way Down", "John Green", 280, 20],
    ["Divergent", "Veronica Roth", 310, 15],
    ["Insurgent", "Veronica Roth", 320, 12],
    ["Allegiant", "Veronica Roth", 330, 11],
    ["The Hunger Games", "Suzanne Collins", 350, 14],
    ["Catching Fire", "Suzanne Collins", 360, 13],
    ["Mockingjay", "Suzanne Collins", 370, 10],
    ["Twilight", "Stephenie Meyer", 300, 17],
    ["New Moon", "Stephenie Meyer", 320, 16],
    ["Eclipse", "Stephenie Meyer", 340, 15],
    ["Breaking Dawn", "Stephenie Meyer", 360, 14],
    ["The Perks of Being a Wallflower", "Stephen Chbosky", 290, 21],
    ["Thirteen Reasons Why", "Jay Asher", 260, 20],
    ["The Giver", "Lois Lowry", 280, 19],
    ["Number the Stars", "Lois Lowry", 260, 18],
    ["The Chronicles of Narnia", "C.S. Lewis", 500, 12],
    ["The Lion, the Witch and the Wardrobe", "C.S. Lewis", 300, 20],
    ["Prince Caspian", "C.S. Lewis", 310, 18],
    ["The Voyage of the Dawn Treader", "C.S. Lewis", 320, 16],
    ["The Silver Chair", "C.S. Lewis", 330, 14],
    ["The Horse and His Boy", "C.S. Lewis", 340, 12],
    ["The Magician's Nephew", "C.S. Lewis", 350, 10],
    ["The Last Battle", "C.S. Lewis", 360, 8],
    ["Percy Jackson & the Olympians: The Lightning Thief", "Rick Riordan", 280, 22],
    ["Percy Jackson & the Olympians: The Sea of Monsters", "Rick Riordan", 290, 20],
    ["Percy Jackson & the Olympians: The Titan's Curse", "Rick Riordan", 300, 18],
    ["Percy Jackson & the Olympians: The Battle of the Labyrinth", "Rick Riordan", 310, 16],
    ["Percy Jackson & the Olympians: The Last Olympian", "Rick Riordan", 320, 14],
    ["The Maze Runner", "James Dashner", 340, 12],
    ["The Scorch Trials", "James Dashner", 350, 10],
    ["The Death Cure", "James Dashner", 360, 9],
    ["The Kill Order", "James Dashner", 370, 8],
    ["The Fever Code", "James Dashner", 380, 7],
    ["The Shining", "Stephen King", 400, 15],
    ["Carrie", "Stephen King", 380, 13],
    ["IT", "Stephen King", 600, 8],
    ["Misery", "Stephen King", 450, 9],
    ["Pet Sematary", "Stephen King", 420, 10],
    ["Doctor Sleep", "Stephen King", 430, 12],
    ["The Outsider", "Stephen King", 410, 13],
    ["Ender's Game", "Orson Scott Card", 300, 19],
    ["Speaker for the Dead", "Orson Scott Card", 320, 18],
    ["Xenocide", "Orson Scott Card", 350, 16],
    ["Children of the Mind", "Orson Scott Card", 370, 14],
    ["Dune", "Frank Herbert", 500, 10],
    ["Dune Messiah", "Frank Herbert", 450, 9],
    ["Children of Dune", "Frank Herbert", 470, 8],
    ["God Emperor of Dune", "Frank Herbert", 490, 6],
    ["Heretics of Dune", "Frank Herbert", 480, 7],
    ["Chapterhouse: Dune", "Frank Herbert", 500, 5],
    ["The Handmaid's Tale", "Margaret Atwood", 350, 13],
    ["Oryx and Crake", "Margaret Atwood", 400, 11],
    ["MaddAddam", "Margaret Atwood", 420, 10]
]



conn = m.connect(host='localhost', user="root", password="1234",database="bookshop")
cn=conn.cursor()
for k in books:
    cn.execute("INSERT INTO books (name, author, price,quantity) VALUES (%s, %s, %s,%s)",(k[0], k[1], k[2],k[3]))
    conn.commit()

conn.close()
